management:
  endpoint:
    health:
      show-details: always

spring:
  profiles:
    active: "dev"

  liquibase:
    check-change-log-location: true
    enabled: true
    change-log: classpath:db/db.changelog-master.xml

  jpa:
    generate-ddl: false
    show-sql: false

server:
  email: brunolviana22@hotmail.com
  port: 8080

---

spring:

  profiles: dev

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/bd_alunos
    username: root
    password: root
    hikari:
      pool-name: alunosPoolCP
      minimum-idle: 5
      maximum-pool-size: 20

---

spring:

  profiles: container

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://banco:3306/bd_alunos
    username: root
    password: root
    hikari:
      pool-name: alunosPoolCP
      minimum-idle: 5
      maximum-pool-size: 20